<?php

return [
    'production' => false,
    'baseUrl' => '',
    'ticketsUrl' => 'https://ti.to/on3/fullstack19 ',
    'collections' => [],
    'venue' => 'Hilton Antwerp Old Town',
    'speakers' => [
        'jeremy-keith' => [
            'url' => 'jeremy-keith',
            'name' => 'Jeremy Keith',
            'twitter' => 'adactio',
            'website' => 'adactio.com',
            'bio' => 'Web stuff do-er at Clearleft',
        ],
        'konstantin-kudryashov' => [
            'url' => 'konstantin-kudryashov',
            'name' => 'Konstantin Kudryashov',
            'twitter' => 'everzet',
            'website' => 'stakeholderwhisperer.com',
            'bio' => 'eXtreme Programmer',
        ],
        'sara-soueidan' => [
            'url' => 'sara-soueidan',
            'name' => 'Sara Soueidan',
            'twitter' => 'sarasoueidan',
            'website' => 'sarasoueidan.com',
            'bio' => 'Front-End UI/UX Developer',
        ],
        'mattias-geniar' => [
            'url' => 'mattias-geniar',
            'name' => 'Mattias Geniar',
            'twitter' => 'mattiasgeniar',
            'website' => 'ma.ttias.be',
            'bio' => 'Problem Solver at Combell',
        ],
        'matthias-noback' => [
            'url' => 'matthias-noback',
            'name' => 'Matthias Noback',
            'twitter' => 'matthiasnoback',
            'website' => 'matthiasnoback.nl',
            'bio' => 'Developer at Noback\'s Office',
            'workshop' => 'Building Autonomous Services',
        ],
        'nataliya-remez' => [
            'url' => 'nataliya-remez',
            'name' => 'Nataliya Remez',
            'twitter' => 'nat_remez',
            'website' => 'izettle.com',
            'bio' => 'Agile Coach at iZettle',
        ],
        'gabi-davila' => [
            'url' => 'gabi-davila',
            'name' => 'Gabi D\'Ávila Ferrara',
            'twitter' => 'gabidavila',
            'website' => 'gabi.dev',
            'bio' => 'Developer Advocate at Google Cloud',
        ],
        'rik-van-bruggen' => [
            'url' => 'rik-van-bruggen',
            'name' => 'Rik Van Bruggen',
            'twitter' => 'rvanbruggen',
            'website' => 'blog.bruggen.com',
            'bio' => 'Vice-president at Neo4j',
        ],
        'mathias-verraes' => [
            'url' => 'mathias-verraes',
            'name' => 'Mathias Verraes',
            'twitter' => 'mathiasverraes',
            'website' => 'verraes.net',
            'httpWebsite' => true,
            'bio' => 'Student of Systems',
            'workshop' => 'DDD Modelling vs Implementation',
        ],
        'indu-alagarsamy' => [
            'url' => 'indu-alagarsamy',
            'name' => 'Indu Alagarsamy',
            'twitter' => 'indu_alagarsamy',
            'website' => 'indu.dev',
            'bio' => 'Distributed Systems Engineer',
        ],
        'caleb-porzio' => [
            'url' => 'caleb-porzio',
            'name' => 'Caleb Porzio',
            'twitter' => 'calebporzio',
            'website' => 'calebporzio.com',
            'bio' => 'Full Stack Developer',
        ],
        'thijs-feryn' => [
            'url' => 'thijs-feryn',
            'name' => 'Thijs Feryn',
            'twitter' => 'ThijsFeryn',
            'website' => 'feryn.eu',
            'bio' => 'Evangelist at Varnish Software',
        ],
    ],
];
