name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer install --prefer-dist --no-interaction

      - name: Install Yarn dependencies
        run: yarn

      - name: Install 2019 dependencies
        run: ./node_modules/.bin/nps setup:2019

      - name: Install 2021 dependencies
        run: ./node_modules/.bin/nps setup:2021

      - name: Install 2022 dependencies
        run: ./node_modules/.bin/nps setup:2022

      - name: Compile dependencies
        run: yarn production

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
